#!/bin/bash
if [ "$#" -lt 1 ]; then
    echo "Illegal number of parameters"
    echo "Usage: " $0 "<roll number>"
    exit 1
fi

CLASS=CS3020
ASN_NO=2
ROLL_NO=$(tr '[:lower:]' '[:upper:]' <<< "$1")

FILES="PA2/README PA2/*.cl PA2/cool.flex"

FILE_NAME=${CLASS}_Prgm_Asn${ASN_NO}_${ROLL_NO}.tar.gz

tar cjvf $FILE_NAME $FILES
